name: Docker Image fly.io Deploy.

on:
  workflow_dispatch:
    inputs:
      fly-toml:
        required: true
        type: string
      authentication-config-yml:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ inputs.docker_user }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
    - name: login docker
      run: echo ${{ inputs.docker_password }} | docker login -u ${{ inputs.docker_user }} --password-stdin
    - name: Push the Docker image
      run: docker push ${{ inputs.docker_user }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
