name: Docker Image fly.io Deploy.

on:
  workflow_dispatch:
    inputs:
      authentication_config_yml:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install fly.io
      run: curl -L https://fly.io/install.sh | sh
    - name: fly.io 
      run: /home/runner/.fly/bin/flyctl version
    - name: fly.io login
      run: /home/runner/.fly/bin/flyctl auth login
    - name: fly.io Auth Whoami
      run: /home/runner/.fly/bin/flyctl auth whoami
    - name: fly.io Auth status
      run: /home/runner/.fly/bin/flyctl status -c /home/runner/work/docker-caddy/docker-caddy/other/fly.toml
    
