name: Docker Image fly.io Updated Deploy.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Install fly.io
      run: |
        ls la
        curl -L https://fly.io/install.sh | sh
        /home/runner/.fly/bin/flyctl version

