name: Docker Image fly.io Deploy.

on:
  workflow_dispatch:
    inputs:
      fly-toml:
        required: true
        type: string
      authentication-config-yml:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install fly.io
      run: curl -L https://fly.io/install.sh | sh
    - name: fly.io 
      run: /home/runner/.fly/bin/flyctl version
    - name: fly.io Authentication
      run: echo ${{ inputs.docker_user }} > /home/runner/.fly/config.yml
    - name: Auth Whoami
      run: /home/runner/.fly/bin/flyctl auth whoami
